- package-lock.json
- package.json
- src/get-oauth-authentication.ts
- test/index.test.ts
Fixes #26.
I've added a test and a fix. Let me know if you had something else in mind.
Jest is reporting missing branch coverage because I'm not testing the default value in case the response does not include an `error_description`. I introduced the default value just in case, but the [documentation](https://developer.github.com/apps/managing-oauth-apps/troubleshooting-oauth-app-access-token-request-errors/) I could find seems to always include `error_description`, so maybe it's not necessary.
> Handle errors in OAuth endpoint

- src/hook.ts
> auth.hook() uses app auth for "https://api.github.com/app/installations"

- README.md
> docs(README): add not about `permissions` option for `auth()` / GHES 2.18

- README.md
GitHub uses a slightly different hash here.
> Fix auth.hook link in README table of contents

- README.md
- src/get-installation-authentication.ts
- test/index.test.ts
An installationId is required in either `createAuthApp` or `auth` when using the installation auth type. This adds an error message to warn users when an installationId is missing.
Closes #64
> fix: throw helpful error on `auth({ type: "installation" })` if `installationId` option is not set

- src/cache.ts
- test/index.test.ts
This should workaround errors I see in production apps that seem to have permissions set in some cases
> fix: do not remail trailing | from cache values

- src/hook.ts
- test/index.test.ts
> feat: improve error message in case of 401 after the retries in the first 5 seconds

- src/auth.ts
- src/get-app-authentication.ts
- src/get-installation-authentication.ts
- src/hook.ts
- src/types.ts
- test/index.test.ts
This adds error handling behavior for when app authentication fails due
to a mismatch in system times between the local machine and GitHub's API
servers. If an expiration (exp) or issued_at (iat) claim in the JWT
payload is invalid, the difference between the system time and GitHub's
server time is stored and further requests are made with JWTs that
include that time difference when creating the exp and iat claims.
Also, this is pending on changes in https://github.com/gr2m/universal-github-app-jwt/pull/28. I tested it locally by `npm link`ing the changes from that PR into this branch so the tests should pass when those changes get merged in. If there's any changes in that PR I'll update the library usage in this one too.
fixes https://github.com/octokit/auth-app.js/issues/146
fixes …
> fix(app authentication): Handle time difference between system and GitHub API time in JWT claims

- src/get-installation-authentication.ts
- src/index.ts
- src/types.ts
- test/index.test.ts
> feat: accept `id` and `installationId` options to be strings

- src/types.ts
This moves the `timeDifference` key from `StrategyOptions` to `State`.
This is because `timeDifference` is only used internally in the state
object and not passed in by the user in the options parameter to
auth-app.
The types were not failing previously because the `State` type extends
the `StrategyOptions` type. However, `State` is the correct place for
this key to live.
Closes #199
> fix(typescript): timeDifference is not a valid parameter

- README.md
- package.json
- src/get-app-authentication.ts
- src/get-installation-authentication.ts
- src/index.ts
- src/types.ts
- test/deprecations.test.ts
- test/index.test.ts
`strategyOptions.id` is now deprecated. Fixes #44
> feat: `strategyOptions.id` is now `strategyOptions.appId`

- package-lock.json
- src/get-installation-authentication.ts
- src/types.ts
- test/index.test.ts
If any extra options are passed to the strategy options, they will be passed through to the `factory` method in `auth({ type: "installation", factory })`. This makes sure that the `octokit` and `octokitOptions` options that `@octokit/core` now passes automatically since https://github.com/octokit/core.js/pull/233 will be passed to the `factory` for easier constructon of a new `octokit` instance
> feat: pass all strategy options to auth `factory`

- README.md
No longer needed as it graduated to the offical API on 2020-08-20.
https://developer.github.com/changes/2020-08-20-graduate-machine-man-and-sailor-v-previews/
> docs(README): add note on graduated `machine-man` preview

- src/auth.ts
- test/index.test.ts
throw Error when auth type is not a valid one
Fix #216
> feat(auth): throw Error when auth type is not a valid one

- README.md
- package-lock.json
- src/cache.ts
- src/get-installation-authentication.ts
- src/to-token-authentication.ts
- src/types.ts
- test/index.test.ts
> feat(repositoryNames) Able to filter out what repos the Installation Token has access to via repo name

- README.md
- package-lock.json
- package.json
- src/auth.ts
- src/index.ts
- src/types.ts
- test/deprecations.test.ts
- test/index.test.ts
- test/typescript-validate.ts
This PR has currently only a failing test and needs the implementation for the actual fix
fixes #282
> fix(typescript): installation authentication type

- src/types.ts
> fix(typescript): corret types for `auth({ type: "installation", installationId, factory })`

- src/requires-app-auth.ts
Hi,
I'm trying to use the new event redelivery api
The request are not working for me because it seams to want to use the installation token when I use the endpoint:
app/hook/deliveries?status=failure
I tried it from a probot app with:
```
const octokit = await app.auth();
const result2 = await octokit.request("GET /app/hook/deliveries", { status: "failure", mediaType: { previews: [mediaPreview] } });
```
I'm not sure about the other apis, if they need an installation token or an app bearer.
What do you think?
> fix: add webhook deliveries APIs

- src/get-app-authentication.ts
- test/index.test.ts
- To improve error message when `privateKey` provided by a user is incomplete (with only `-----BEGIN RSA PRIVATE KEY-----`)
Fix #311
> feat(get-app-authentication): improve error message when privateKey is incomplete

- package-lock.json
- package.json
Fix #351 
---
I expect to address the proper fix with `sinonjs/fake-timers v9` when Renovate generates the associated PR.
> ci(test): downgrade sinonjs/faker-timers to v8 to 'test' checkrun

- src/index.ts
- test/index.test.ts
Currently the `appId` is checked only for a _truthy_ value, but it's actually required to be numeric, as well - [`getAppAuthentication`](https://github.com/octokit/auth-app.js/blob/524fc446d33ae5acfde702153adb127e8d786df9/src/get-app-authentication.ts#L12) assumes it is. If it is not, it results in the `iss` property of the JWT being set to `NaN` and causing an authentication failure. 
This adds an additional check to make sure `appId` is a finite number or can be coerced into a finite number.
partly addresses https://github.com/octokit/auth-app.js/issues/375
> fix: throw helpful error when `appId` is not numeric

- package-lock.json
- package.json
Resolves #430
----
* [The jsonwebtoken v8.5.1 package is reporting a high security vulnerability when running `npm audit`.](https://github.com/octokit/octokit.js/issues/2373)
* `npm audit` stops reporting a high security vulnerability for `jsonwebtoken`
* You can find more context in this other issue: https://github.com/octokit/octokit.js/issues/2373
----
Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!
If `Yes`, what's the impact:  
* N/A
`Type: Maintenance`
----
> fix(deps): upgrade universal-github-app-jwt to v1.1.1

- src/requires-app-auth.ts
- test/index.test.ts
This fixed a bug where App authentication was occurring when attempting to get the list of installed apps in an organization. I have also tested the scenario where query strings are present, which was a concern raised in an issue. 
I am not very familiar with this library, so I would appreciate it if someone could thoroughly review it.
Resolves #374 (with @snicmakino)
> fix: `requiresAppAuth` was matching unintended URLs.

- test/index.test.ts
Resolves #506
----
Test assertions of Responses from `fetch-mock` are done with `jest.toMatchObject`
Test assertions of Responses from `fetch-mock` are done with `jest.toEqual`
More context in https://github.com/octokit/core.js/issues/588
----
Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/main/community/breaking_changes.md) to help!
If `Yes`, what's the impact:
* N/A
`Type: Maintenance`
----
> test(refactor): test(refactor): use 'toEqual' instead of 'toMatchObject' for Responses

- package.json
- scripts/build.mjs
- src/auth.ts
- src/get-app-authentication.ts
- src/get-installation-authentication.ts
- src/hook.ts
- src/index.ts
- src/to-token-authentication.ts
- test/deprecations.test.ts
- test/index.test.ts
- test/smoke.test.ts
- test/tsconfig.test.json
This PR replaces NodeJS internal module imports with `node:` specifier imports.
> refactor: replace NodeJS internal module imports with `node:` specifier imports

- src/requires-app-auth.ts
Resolves #593
Ensures [List Installation Requests for the Authenticated App](https://docs.github.com/en/rest/apps/apps?apiVersion=2022-11-28#list-installation-requests-for-the-authenticated-app) use an app JWT
Octokit requests to `GET /app/installation-requests` will throw the following error:
```
Error: [@octokit/auth-app] installationId option is required for installation authentication.
```
Octokit requests to `GET /app/installation-requests` will make the request with an app JWT.
Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!
----
> fix: add /app/installation-requests to requires-app-auth paths

- .github/workflows/release.yml
- package-lock.json
- package.json
- src/get-app-authentication.ts
- src/index.ts
- src/types.ts
- test/index.test.ts
- test/typescript-validate.ts
- **feat(types): `appId` allows string or number as type**
- **test(types): add test coverage for appId new type**
Resolves #603 
----
`appId` only allowed `number` as type.
`appId` allows `number` or `string` as type.
Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!
----
> feat: `appId` argument can be set to Client ID string

- src/hook.ts
- test/index.test.ts
> fix: respect `baseUrl` passed as part of request parameters

- package-lock.json
- package.json
See https://github.com/isaacs/node-lru-cache/issues/355
Resolves #ISSUE_NUMBER
----
* Type errors would occur when building or consuming the package
* Use a fork of `lru-cache` that backports the required fix for the type issues
Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!
----
> fix(deps): use fork of `lru-cache` to fix type errors

- package-lock.json
- package.json
- src/cache.ts
- src/types.ts
This replaces lru-cache with toad-cache by @kibertoad
We use this in fastify and have good experience with it.
> fix: replace lru-cache with toad-cache
